# Generated by Django 4.1 on 2023-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price_with_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price_without_tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
