# Generated by Django 4.1 on 2023-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_total_price_with_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(blank=True, null=True, to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
