# Generated by Django 4.1 on 2023-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_items_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='reference',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
